import MainLayout from '@/components/MainLayout'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

export const metadata: Metadata = {
	title: "Zy's Dashboard",
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<MainLayout>{children}</MainLayout>
			</body>
		</html>
	)
}
